### PR TITLE
room: allow RemoteParticipant to be None

### PR DESCRIPTION
**Pull request by nbsp**
should fix the bug when receiving messages from the server: this allows Python to fail gracefully to retrieve the remote participant.

### CODE REVIEW

**Review by davidzhao — APPROVED** [review]

**Comment by davidzhao** [comment]
looks like we need to update the return type too

**Review by theomonnom — APPROVED** [review]
Lgtm, CI doesn't pass tho

**Comment by nbsp** [comment]
> looks like we need to update the return type too

where? the return type on this specific function is Optional[] now, and as far as i can tell the rest are already like that too

**Comment by nbsp** [comment]
unsure why this is still erroring, i've got `assert isinstance` guards there..

**Comment by davidzhao** [comment]
> unsure why this is still erroring, i've got `assert isinstance` guards there..

have you tried `isinstance(obj, Participant)` or `if obj is not None` ?

**Comment by nbsp** [comment]
> > unsure why this is still erroring, i've got `assert isinstance` guards there..
> 
> have you tried `isinstance(obj, Participant)` or `if obj is not None` ?

found a fix by using typing.cast

**Pull request merged**
